name: task_dart_hive_db_prototype
description: Prototype library to explore writing a taskwarrior client using Hive db library

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  hive:
  path:
  taskc:
    git:
      url: https://github.com/bradyt/taskd-client-dart.git

dev_dependencies:
  pedantic:
  test:
